subject: cn=client-ca
---
subject: cn=server-ca
---
subject: cn=server-sub-ca
ca: true
issuer: cn=server-ca
---
subject: cn=client
issuer: cn=client-ca
crl_distribution_points:
  - http://localhost:8080/client-ca-crl.pem
---
subject: cn=revoked-client
issuer: cn=client-ca
revoked: true
crl_distribution_points:
  - http://localhost:8080/client-ca-crl.pem
---
subject: cn=server
issuer: cn=server-sub-ca
#not_before: 2020-01-01T09:00:00Z
#not_after: 2020-02-01T10:10:10Z
sans:
  - DNS:server.127-0-0-1.nip.io
  - DNS:localhost
#  - DNS:unexpected-name
